//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public System.DateTime AddedAt { get; set; }
        public int FranchiseId { get; set; }
        public int UserId { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual User User { get; set; }
    }
}
