//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> FeedbackStatusId { get; set; }
        public string UserId { get; set; }
    
        public virtual FeedbackStatus FeedbackStatus { get; set; }
    }
}
