//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Franchise()
        {
            this.Favorites = new HashSet<Favorite>();
            this.FranchiseTags = new HashSet<FranchiseTag>();
            this.Orders = new HashSet<Order>();
            this.PriceHistories = new HashSet<PriceHistory>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int FranchiseId { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public decimal PledgeAmount { get; set; }
        public decimal InvestmentAmount { get; set; }
        public int PaybackPeriod { get; set; }
        public decimal RoyaltyPercent { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public decimal FinalPrice { get; set; }
        public string Description { get; set; }
        public string MinPhotoUrl { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CategoryId { get; set; }
        public int FranTypeId { get; set; }
        public int PremTypesId { get; set; }
        public int FranStatusId { get; set; }
        public int FranchiserId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual Franchiser Franchiser { get; set; }
        public virtual FranStatus FranStatus { get; set; }
        public virtual FranType FranType { get; set; }
        public virtual PremTypes PremTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FranchiseTag> FranchiseTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
