//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseTag
    {
        public int FranchiseTagId { get; set; }
        public int FranchiseId { get; set; }
        public int TagId { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
