//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FranchiseDBEntities1 : DbContext
    {
        public FranchiseDBEntities1()
            : base("name=FranchiseDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ContactMethod> ContactMethods { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FeedbackStatus> FeedbackStatuses { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Franchiser> Franchisers { get; set; }
        public virtual DbSet<Franchise> Franchises { get; set; }
        public virtual DbSet<FranchiseTag> FranchiseTags { get; set; }
        public virtual DbSet<FranStatus> FranStatuses { get; set; }
        public virtual DbSet<FranType> FranTypes { get; set; }
        public virtual DbSet<ModerSt> ModerSts { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsStatus> NewsStatuses { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatuses { get; set; }
        public virtual DbSet<PremTypes> PremTypeses { get; set; }
        public virtual DbSet<PriceHistory> PriceHistories { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatus> UserStatuses { get; set; }
    }
}
