//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string OrderNumber { get; set; }
        public string Comments { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int FranchiseId { get; set; }
        public int UserId { get; set; }
        public int OrderStatusId { get; set; }
        public int RegionId { get; set; }
        public int ContactMethodId { get; set; }
        public Nullable<int> UsersUserId { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual ContactMethod ContactMethod { get; set; }
        public virtual File File { get; set; }
        public virtual Franchise Franchise { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Region Region { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
