//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranchAdm.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int PriceHistoryId { get; set; }
        public decimal OldPrice { get; set; }
        public decimal NewPrice { get; set; }
        public System.DateTime ChangeAd { get; set; }
        public string Reason { get; set; }
        public int FranchiseId { get; set; }
    
        public virtual Franchise Franchise { get; set; }
    }
}
