// <auto-generated />
using System;
using FranchiseAgregator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FranchiseAgregator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeedbackStatus", b =>
                {
                    b.Property<int>("FeedbackStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FeedbackStatusId");

                    b.ToTable("FeedbackStatus");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.ContactMethod", b =>
                {
                    b.Property<int>("ContactMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactMethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactMethodId");

                    b.ToTable("ContactMethods");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.DbFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackStatusId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.FranStatus", b =>
                {
                    b.Property<int>("FranStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranStatusId");

                    b.ToTable("FranStatuses");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.FranType", b =>
                {
                    b.Property<int>("FranTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranTypeId");

                    b.ToTable("FranTypes");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiseId"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FranStatusId")
                        .HasColumnType("int");

                    b.Property<int>("FranTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FranchiserId")
                        .HasColumnType("int");

                    b.Property<decimal>("InvestmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MinPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaybackPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("PledgeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PremTypesId")
                        .HasColumnType("int");

                    b.Property<decimal>("RoyaltyPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("FranchiseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FranStatusId");

                    b.HasIndex("FranTypeId");

                    b.HasIndex("FranchiserId");

                    b.HasIndex("PremTypesId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.FranchiseTag", b =>
                {
                    b.Property<int>("FranchiseTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiseTagId"));

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("FranchiseTagId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("TagId");

                    b.ToTable("FranchiseTags");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Franchiser", b =>
                {
                    b.Property<int>("FranchiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiserId"));

                    b.Property<string>("Contacts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranchiserId");

                    b.ToTable("Franchisers");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.ModerSt", b =>
                {
                    b.Property<int>("ModerStId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModerStId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModerStId");

                    b.ToTable("ModerSts");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewsStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsId");

                    b.HasIndex("NewsStatusId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.NewsStatus", b =>
                {
                    b.Property<int>("NewsStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NewsStatusId");

                    b.ToTable("NewsStatuses");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactMethodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ContactMethodId");

                    b.HasIndex("FileId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.PremTypes", b =>
                {
                    b.Property<int>("PremTypesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PremTypesId"));

                    b.Property<decimal?>("MinArea")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PremTypesId");

                    b.ToTable("PremTypeses");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.PriceHistory", b =>
                {
                    b.Property<int>("PriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceHistoryId"));

                    b.Property<DateTime>("ChangeAd")
                        .HasColumnType("datetime2");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceHistoryId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("ModerStId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ModerStId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.UserStatus", b =>
                {
                    b.Property<int>("UserStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserStatusId");

                    b.ToTable("UserStatuses");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Favorite", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.Franchise", "Franchise")
                        .WithMany("Favorites")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Users", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Feedback", b =>
                {
                    b.HasOne("FeedbackStatus", "Status")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FeedbackStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Franchise", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.Category", "Category")
                        .WithMany("Franchises")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.FranStatus", "FranStatus")
                        .WithMany("Franchises")
                        .HasForeignKey("FranStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.FranType", "FranType")
                        .WithMany("Franchises")
                        .HasForeignKey("FranTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Franchiser", "Franchiser")
                        .WithMany("Franchises")
                        .HasForeignKey("FranchiserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.PremTypes", "PremTypes")
                        .WithMany("Franchises")
                        .HasForeignKey("PremTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FranStatus");

                    b.Navigation("FranType");

                    b.Navigation("Franchiser");

                    b.Navigation("PremTypes");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.FranchiseTag", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.Franchise", "Franchise")
                        .WithMany("FranchiseTags")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Tag", "Tag")
                        .WithMany("FranchiseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.News", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.NewsStatus", "Status")
                        .WithMany("News")
                        .HasForeignKey("NewsStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Order", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.ContactMethod", "ContactMethod")
                        .WithMany("Orders")
                        .HasForeignKey("ContactMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.DbFile", "File")
                        .WithMany("Orders")
                        .HasForeignKey("FileId");

                    b.HasOne("FranchiseAgregator.Models.Franchise", "Franchise")
                        .WithMany("Orders")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Region", "Region")
                        .WithMany("Orders")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Users", "Client")
                        .WithMany("OrdersAsClient")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Users", null)
                        .WithMany("OrdersAsManager")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Client");

                    b.Navigation("ContactMethod");

                    b.Navigation("File");

                    b.Navigation("Franchise");

                    b.Navigation("OrderStatus");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.PriceHistory", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.Franchise", "Franchise")
                        .WithMany("PriceHistories")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Review", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.Franchise", "Franchise")
                        .WithMany("Reviews")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.ModerSt", "ModerSt")
                        .WithMany("Reviews")
                        .HasForeignKey("ModerStId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.Users", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("ModerSt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Users", b =>
                {
                    b.HasOne("FranchiseAgregator.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranchiseAgregator.Models.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("FeedbackStatus", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Category", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.ContactMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.DbFile", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.FranStatus", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.FranType", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Franchise", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("FranchiseTags");

                    b.Navigation("Orders");

                    b.Navigation("PriceHistories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Franchiser", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.ModerSt", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.NewsStatus", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.PremTypes", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Region", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Tag", b =>
                {
                    b.Navigation("FranchiseTags");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FranchiseAgregator.Models.Users", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("OrdersAsClient");

                    b.Navigation("OrdersAsManager");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
